config/routes.rb
Rails.application.routes.draw do
  resources :subscription_notifications
  get 'feed_item/show/:id' => 'feed_item#show', as: :feed_item

  get 'feed_item/clean'

  get 'improve_sanitization/show'

  get 'read_mode/index'
  get 'read_mode/vue'
  get 'read_mode/get'
  get 'read_mode/stats'
  post 'read_mode/mark_item_as_read'

  get 'cache_all_feeds' => 'subscriptions#cache_all_feeds', as: :cache_all_feeds
  get 'enqueue_cache_all_feeds' => 'subscriptions#enqueue_cache_all_feeds', as: :enqueue_cache_all_feeds
  delete 'destroy_all_subscriptios' => 'subscriptions#destroy_all_subscriptions', as: :destroy_all_subscriptions
  delete 'destroy_all_articles' => 'subscriptions#destroy_all_feed_items', as: :destroy_all_articles
  delete 'mark_all_read' => 'subscriptions#mark_all_read', as: :mark_all_read

  resources :subscriptions do
    resources :subscription_notifications do
      collection do
        delete 'destroy_all_subscription_notifications'
      end
    end

    member do
      get 'cache_feed'
      put 'mark_all_read_for_subscription'
    end
  end

  get 'opml_import/index'
  post 'opml_import/import'

  devise_for :users

  root 'read_mode#index'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/subscription_notification.rb
class SubscriptionNotification < ActiveRecord::Base
end

app/controllers/subscription_notifications_controller.rb
class SubscriptionNotificationsController < ApplicationController
  before_action :set_subscription_notification, only: [:show, :edit, :update, :destroy]

  # GET /subscription_notifications
  # GET /subscription_notifications.json
  def index
    @subscription_notifications = SubscriptionNotification.where(subscription_id: params[:subscription_id]).all
  end

  # GET /subscription_notifications/1
  # GET /subscription_notifications/1.json
  def show
  end

  # GET /subscription_notifications/new
  def new
    @subscription_notification = SubscriptionNotification.new
  end

  # GET /subscription_notifications/1/edit
  def edit
  end

  # POST /subscription_notifications
  # POST /subscription_notifications.json
  def create
    @subscription_notification = SubscriptionNotification.new(subscription_notification_params)

    respond_to do |format|
      if @subscription_notification.save
        format.html { redirect_to @subscription_notification, notice: 'Subscription notification was successfully created.' }
        format.json { render :show, status: :created, location: @subscription_notification }
      else
        format.html { render :new }
        format.json { render json: @subscription_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscription_notifications/1
  # PATCH/PUT /subscription_notifications/1.json
  def update
    respond_to do |format|
      if @subscription_notification.update(subscription_notification_params)
        format.html { redirect_to @subscription_notification, notice: 'Subscription notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription_notification }
      else
        format.html { render :edit }
        format.json { render json: @subscription_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscription_notifications/1
  # DELETE /subscription_notifications/1.json
  def destroy
    @subscription_notification.destroy
    respond_to do |format|
      format.html { redirect_to subscription_notifications_url, notice: 'Subscription notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all_subscription_notifications
    @subscription = Subscription.find(params[:subscription_id])
    @subscription.subscription_notifications.find_each do |subscription_notification|
      subscription_notification.destroy
    end
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscriptions notifications were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription_notification
      @subscription_notification = SubscriptionNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_notification_params
      params[:subscription_notification].permit(:subscription_id)
    end
end

app/helpers/subscription_notifications_helper.rb
module SubscriptionNotificationsHelper
end

app/views/subscription_notifications/_form.html.slim
= form_for @subscription_notification do |f|
  - if @subscription_notification.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subscription_notification.errors.count, "error")} prohibited this subscription_notification from being saved:"
      ul
        - @subscription_notification.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/subscription_notifications/edit.html.slim
h1 Editing subscription_notification

== render 'form'

= link_to 'Show', @subscription_notification
'|
= link_to 'Back', subscription_notifications_path

app/views/subscription_notifications/index.html.slim
h1 Listing subscription_notifications
table class="table table-hover table-striped"
  tbody
    tr
      td
        b Subscriptions Notifications
      td = @subscription_notifications.count
      td = link_to 'delete all', destroy_all_subscription_notifications_subscription_subscription_notifications_path, class: 'btn btn-danger btn-sm', method: :delete
      td

table
  thead
    tr
      th Date
      th Body
      th
      th
      th

  tbody
    - @subscription_notifications.each do |subscription_notification|
      tr
        td = subscription_notification.created_at
        td = subscription_notification.body.gsub(/\n/, '<br />').html_safe
        td = link_to 'Show', subscription_notification
        td = link_to 'Edit', edit_subscription_notification_path(subscription_notification)
        td = link_to 'Destroy', subscription_notification, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/subscription_notifications/new.html.slim
h1 New subscription_notification

== render 'form'

= link_to 'Back', subscription_notifications_path

app/views/subscription_notifications/show.html.slim
p#notice = notice


= link_to 'Edit', edit_subscription_notification_path(@subscription_notification)
'|
= link_to 'Back', subscription_notifications_path