config/routes.rb
Rails.application.routes.draw do
  resources :subscription_notifications
  get 'feed_item/show/:id' => 'feed_item#show', as: :feed_item

  get 'feed_item/clean'

  get 'improve_sanitization/show'

  get 'read_mode/index'
  get 'read_mode/vue'
  get 'read_mode/get'
  get 'read_mode/stats'
  post 'read_mode/mark_item_as_read'

  get 'cache_all_feeds' => 'subscriptions#cache_all_feeds', as: :cache_all_feeds
  get 'enqueue_cache_all_feeds' => 'subscriptions#enqueue_cache_all_feeds', as: :enqueue_cache_all_feeds
  delete 'destroy_all_subscriptios' => 'subscriptions#destroy_all_subscriptions', as: :destroy_all_subscriptions
  delete 'destroy_all_articles' => 'subscriptions#destroy_all_feed_items', as: :destroy_all_articles
  delete 'mark_all_read' => 'subscriptions#mark_all_read', as: :mark_all_read

  resources :subscriptions do
    resources :subscription_notifications do
      collection do
        delete 'destroy_all_subscription_notifications'
      end
    end

    member do
      get 'cache_feed'
      put 'mark_all_read_for_subscription'
    end
  end

  get 'opml_import/index'
  post 'opml_import/import'

  devise_for :users

  root 'read_mode#index'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  has_many :feed_items, dependent: :destroy
  has_many :subscription_notifications, dependent: :destroy

  acts_as_taggable

  def refresh(limit = 10)
    FeedItemDownloader.cache_feed(self)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy, :cache_feed, :mark_all_read_for_subscription]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cache_feed
    FeedItemDownloader.cache_feed(@subscription)
    redirect_to action: :index
  end

  def cache_all_feeds
    Subscription.all.each do |subscription|
      FeedItemDownloader.cache_feed(subscription)
    end
    redirect_to action: :index
  end

  def enqueue_cache_all_feeds
    RefreshAllSubscriptionsWorker.perform_async
    redirect_to action: :index
  end

  def destroy_all_subscriptions
    Subscription.find_each do |subscription|
      subscription.destroy
    end
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscriptions were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all_feed_items
    FeedItem.destroy_all
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscriptions were successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_all_read
    FeedItem.update_all read: true
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'All marked as read' }
      format.json { head :no_content }
    end
  end

  def mark_all_read_for_subscription
    @subscription.feed_items.update_all read: true, updated_at: Time.now
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: "All marked as read for #{@subscription.name}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:name, :feed_url, :http_url, :tag_list)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for @subscription, class: 'form' do |f|
  - if @subscription.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      ul
        - @subscription.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :feed_url
    = f.text_field :feed_url, class: 'form-control'
  .form-group
    = f.label :http_url
    = f.text_field :http_url, class: 'form-control'
  .form-group
    = f.label :tag_list
    = f.text_field :tag_list, class: 'form-control'
  .actions = f.submit 'Save', class: 'btn btn-primary'

app/views/subscriptions/edit.html.slim
h1 Editing subscription

== render 'form'

= link_to 'Show', @subscription
'|
= link_to 'Back', subscriptions_path

app/views/subscriptions/index.html.slim
.row.col-md-8.col-md-offset-2
  table class="table table-hover table-striped"
    tbody
      tr
        td
          b Subscriptions
        td = Subscription.count
        td = link_to 'New Subscription', new_subscription_path, class: 'btn btn-sm btn-primary'
        td = link_to 'OPML import', opml_import_index_path, class: 'btn btn-sm btn-primary'
        / TODO: add a confirmation here
        td = link_to 'delete all', destroy_all_subscriptions_path, class: 'btn btn-danger btn-sm', method: :delete
        td
      tr
        td
          b Articles
        td = "<b>#{FeedItem.where(read: false).count}</b> (#{FeedItem.count})".html_safe
        td = link_to 'download all', enqueue_cache_all_feeds_path, class: 'btn btn-primary btn-sm'
        td = link_to 'mark all read', mark_all_read_path, class: 'btn btn-danger btn-sm', method: :delete
        td = link_to 'delete all', destroy_all_articles_path, class: 'btn btn-danger btn-sm', method: :delete
        td

.row.col-md-8.col-md-offset-1
  table class="table table-hover table-striped"
    thead
      tr
        th Name
        th Feed url
        th
          span.fa.fa-exclamation-sign
        th
        th
        th
        th
        th
        th Tags

    tbody
      - @subscriptions.each do |subscription|
        tr
          td = link_to subscription_path(subscription) do
            = subscription.name
          td = subscription.feed_url
          - if subscription.subscription_notifications.count != 0
            td= link_to(subscription_subscription_notifications_path(subscription)) do
              span.fa.fa-exclamation-sign.alert-danger
              | &nbsp;
              = subscription.subscription_notifications.count
          - else
            td
          td = "<b>#{subscription.feed_items.where(read: false).count}</b> (#{subscription.feed_items.count})".html_safe
          td = link_to mark_all_read_for_subscription_subscription_path(subscription), method: :put do
            span.fa.fa-check
          td = link_to cache_feed_subscription_path(subscription) do
            span.fa.fa-refresh
          td = link_to edit_subscription_path(subscription) do
            span.fa.fa-pencil
          td = link_to subscription, data: {:confirm => 'Are you sure?'}, :method => :delete
            span.fa.fa-remove style="color: red"
          td = subscription.tag_list

.row

app/views/subscriptions/new.html.slim
h1 New subscription

== render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.slim
p#notice = notice

p
  strong Name:
  = @subscription.name
p
  strong Feed url:
  = @subscription.feed_url
p
  strong Http url:
  = @subscription.http_url
p
  strong Tag list:
  = @subscription.tag_list

= link_to "Edit", edit_subscription_path(@subscription)
'|
= link_to 'Back', subscriptions_path

p

table class="table table-hover table-striped"
  tbody
    tr
      td Title
      td Published At
    - @subscription.feed_items.unread.each do |item|
      tr
        td = link_to feed_item_path(item) do
          = item.title
        td = item.published_at