config/routes.rb
Rails.application.routes.draw do
  resources :subscription_notifications
  get 'feed_item/show/:id' => 'feed_item#show', as: :feed_item

  get 'feed_item/clean'

  get 'improve_sanitization/show'

  get 'read_mode/index'
  get 'read_mode/vue'
  get 'read_mode/get'
  get 'read_mode/stats'
  post 'read_mode/mark_item_as_read'

  get 'cache_all_feeds' => 'subscriptions#cache_all_feeds', as: :cache_all_feeds
  get 'enqueue_cache_all_feeds' => 'subscriptions#enqueue_cache_all_feeds', as: :enqueue_cache_all_feeds
  delete 'destroy_all_subscriptios' => 'subscriptions#destroy_all_subscriptions', as: :destroy_all_subscriptions
  delete 'destroy_all_articles' => 'subscriptions#destroy_all_feed_items', as: :destroy_all_articles
  delete 'mark_all_read' => 'subscriptions#mark_all_read', as: :mark_all_read

  resources :subscriptions do
    resources :subscription_notifications do
      collection do
        delete 'destroy_all_subscription_notifications'
      end
    end

    member do
      get 'cache_feed'
      put 'mark_all_read_for_subscription'
    end
  end

  get 'opml_import/index'
  post 'opml_import/import'

  devise_for :users

  root 'read_mode#index'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/application.html.slim
doctype html
html
  head
  title RRR
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = javascript_pack_tag 'application'
  = csrf_meta_tags

  link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"

  body
    .container-fluid
      .row
        nav.col-sm-3.col-md-2.hidden-xs-down.bg-faded.sidebar
          - if user_signed_in?

            - if Rails.env == 'real'
              p.alert-danger
                | real data
            - if Rails.env == 'development'
              p.alert-success
                | development
            .ul.nav.nav-pills.flex-column
              li.nav-item
                = link_to read_mode_index_path(tag: 'tech'), class: 'nav-link'
                  | tech
                  span#tech-count
                  span.pull-right.hidden-xs.showopacity.fa.fa-th-list style="font-size:16px;"
              li.nav-item
                = link_to read_mode_index_path(tag: 'lifehacker'), class: 'nav-link'
                  | lifehacker
                  span#lifehacker-count
                  span.pull-right.hidden-xs.showopacity.fa.fa-th-list style="font-size:16px;"
              li.nav-item
                = link_to read_mode_index_path(tag: 'rest'), class: 'nav-link'
                  | rest
                  span#rest-count
                  span.pull-right.hidden-xs.showopacity.fa.fa-th-list style="font-size:16px;"
              li.nav-item
                = link_to subscriptions_path, class: 'nav-link'
                  | subscriptions
                  span.pull-right.hidden-xs.showopacity.fa.fa-th-list style="font-size:16px;"
              li.nav-item
                = link_to enqueue_cache_all_feeds_path, class: 'nav-link'
                  | refresh all
                  span.pull-right.hidden-xs.showopacity.fa.fa-refresh style="font-size:16px;"
          - else
            | nothing here
        main.col-sm-8.offset-sm-4.col-md-9.offset-md-3.pt-3

          = yield